apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends-nodeport
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    {{ if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    {{ else }}
    targetPort: {{ .Values.service.port }}
    {{ end }}
    protocol: {{ .Values.service.protocol }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: techtrends
  sessionAffinity: None
  type: {{ .Values.service.typeNodePort }}
status:
  loadBalancer: {}