namespace:
  name: staging

service:
  port: 5111
  nodePort: 30009
  typeNodePort: NodePort

replicaCount: 3

image:
  pullPolicy: Always

recources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
