namespace:
  name: prod

service:
  port: 7111
  nodePort: 30010
  typeNodePort: NodePort

replicaCount: 5

image:
  pullPolicy: Always

recources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"
